package SistemaDeActivos.logic;
// Generated 25-May-2019 01:33:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Dependencia generated by hbm2java
 */
public class Dependencia  implements java.io.Serializable {


     private int codigo;
     private Funcionario funcionario;
     private String nombre;
     private Set<Funcionario> funcionarios = new HashSet<Funcionario>(0);
     private Set<Activo> activos = new HashSet<Activo>(0);
     private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);

    public Dependencia() {
    }

	
    public Dependencia(int codigo, String nombre) {
        this.codigo = codigo;
        this.nombre = nombre;
    }
    public Dependencia(int codigo, Funcionario funcionario, String nombre, Set<Funcionario> funcionarios, Set<Activo> activos, Set<Solicitud> solicituds) {
       this.codigo = codigo;
       this.funcionario = funcionario;
       this.nombre = nombre;
       this.funcionarios = funcionarios;
       this.activos = activos;
       this.solicituds = solicituds;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Funcionario> getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set<Funcionario> funcionarios) {
        this.funcionarios = funcionarios;
    }
    public Set<Activo> getActivos() {
        return this.activos;
    }
    
    public void setActivos(Set<Activo> activos) {
        this.activos = activos;
    }
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }




}


