package SistemaDeActivos.logic;
// Generated 25-May-2019 01:33:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private String id;
     private Dependencia dependencia;
     private String nombre;
     private Set<Activo> activos = new HashSet<Activo>(0);
     private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<Dependencia> dependencias = new HashSet<Dependencia>(0);

    public Funcionario() {
    }

	
    public Funcionario(String id, Dependencia dependencia) {
        this.id = id;
        this.dependencia = dependencia;
    }
    public Funcionario(String id, Dependencia dependencia, String nombre, Set<Activo> activos, Set<Solicitud> solicituds, Set<Usuario> usuarios, Set<Dependencia> dependencias) {
       this.id = id;
       this.dependencia = dependencia;
       this.nombre = nombre;
       this.activos = activos;
       this.solicituds = solicituds;
       this.usuarios = usuarios;
       this.dependencias = dependencias;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Dependencia getDependencia() {
        return this.dependencia;
    }
    
    public void setDependencia(Dependencia dependencia) {
        this.dependencia = dependencia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Activo> getActivos() {
        return this.activos;
    }
    
    public void setActivos(Set<Activo> activos) {
        this.activos = activos;
    }
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
    public Set<Dependencia> getDependencias() {
        return this.dependencias;
    }
    
    public void setDependencias(Set<Dependencia> dependencias) {
        this.dependencias = dependencias;
    }




}


