package SistemaDeActivos.logic;
// Generated 25-May-2019 01:33:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String id;
     private Funcionario funcionario;
     private String clave;
     private String rol;
     private Set<Grupo> grupos = new HashSet<Grupo>(0);

    public Usuario() {
    }

	
    public Usuario(String id, Funcionario funcionario) {
        this.id = id;
        this.funcionario = funcionario;
    }
    public Usuario(String id, Funcionario funcionario, String clave, String rol, Set<Grupo> grupos) {
       this.id = id;
       this.funcionario = funcionario;
       this.clave = clave;
       this.rol = rol;
       this.grupos = grupos;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public Set<Grupo> getGrupos() {
        return this.grupos;
    }
    
    public void setGrupos(Set<Grupo> grupos) {
        this.grupos = grupos;
    }




}


